name: CI

on:
  push:
    branches:
    - master

jobs:
  test:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: .\src\main\java\de\jedox\powershell.ps1 
      shell: powershell
